apiVersion: v1
kind: Service
metadata:
  name: equipos
  labels:
    app: equipos
spec:
  selector:
    app: equipos
  ports:
    - name: http
      port: 9080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP