services:
  equipos1:
    container_name: equipos1
    image: mauron/equipos:4
    ports:
      - "9080:8080"
    volumes:
      - ./share:/u01
    environment:
      - DB_HOST=postgres14
      - DB_PORT=5432
      - DB_NAME=equiposdb
      - DB_USER=postgres
      - DB_PASSWORD=123456789
    networks:
      - micros

networks:
  micros:
    external: true